### ISSUE TITLE
Syncing UserDefaults and NSUbiquitousKeyValueStore

### ISSUE THREAD

**Issue by gloparco** [JosephDuffy/Persist#30]
Excellent work!  Might I suggest support for UserDefaults & NSUbiquitousKeyValueStore synchronization?  So, the user just needs to persist UserDefaults with a sync flag (or something similar), and all key/values in UserDefaults will be saved to NSUbiquitousKeyValueStore, or vice versa, depending on a Date value which determines which is more recent.

**Comment by JosephDuffy** [comment]
In general I don't think this is I would like support/encourage. Unless there are usecases for this I'm not aware of but in general `NSUbiquitousKeyValueStore` should cover this requirement (it supports local/offline storage, even when the user is not logged in to iCloud).

If you need this behaviour it would be possible by providing a custom `Storage` class. I don't think you could use the existing `UserDefaultsStorage` or `NSUbiquitousKeyValueStoreStorage` classes though because the types are quite restrictive.

This is because user defaults supports storage of `URL`s (as `Data`), which `NSUbiquitousKeyValueStore` does not. `NSUbiquitousKeyValueStore` also stores `Int64` in place of `UserDefault`'s `Int`. Even though this would be directly convertible `Persist` uses `UserDefaultsValue`, `StorableInUserDefaultsValue`, `NSUbiquitousKeyValueStore`, and `StorableInNSUbiquitousKeyValueStore` internally for type safety, and they do not support direct translation.

**Comment by gloparco** [comment]
While NSUbiquitousKeyValueStore **should** cover this requirement, I believe there are edge cases where this is not true.  See this Stack Overflow question for some interesting comments:

[https://stackoverflow.com/questions/43620573/nsubiquitouskeyvaluestore-vs-nsuserdefaults](https://stackoverflow.com/questions/43620573/nsubiquitouskeyvaluestore-vs-nsuserdefaults)

I think there are other similar repos to yours that tackle this problem, which is why I thought it might be worth adding.  But it's definitely a headache to keep local and cloud in sync, so it's understandable if you feel it's not worth the effort to do so.

In any case, thanks for your response. 🙂

**Comment by JosephDuffy** [comment]
> While NSUbiquitousKeyValueStore **should** cover this requirement, I believe there are edge cases where this is not true. See this Stack Overflow question for some interesting comments:
> 
> [stackoverflow.com/questions/43620573/nsubiquitouskeyvaluestore-vs-nsuserdefaults](https://stackoverflow.com/questions/43620573/nsubiquitouskeyvaluestore-vs-nsuserdefaults)

This brings up that it becomes read-only when the user turns off iCloud for the app, but I don't think the best way to fix this is to sync the 2, but fallback to user defaults when this occurs. It would be unfortunate if it does become read-only is the case but also wouldn't surprise me.

From the docs I don't see how to detect this (maybe `CKContainer.default().accountStatus` would be necessary), but it doesn't sound too hard to reproduce on-device.

> I think there are other similar repos to yours that tackle this problem, which is why I thought it might be worth adding. But it's definitely a headache to keep local and cloud in sync, so it's understandable if you feel it's not worth the effort to do so.

If you can point me to any it may help with an implementation.

I'm particularly interested in how they would solve conflict resolution if they don't know _when_ a value was set.

---

The best way to implement this might be to support fallbacks, so any storage can fallback to any other storage. The trickiest part would likely be getting the _latest_ value because I don't think there's a way to know when a user defaults value was set.

**Comment by gloparco** [comment]
I haven't looked through the source code on this project, but it _appears_ to sync the two:

[Zephyr](https://github.com/ArtSabintsev/Zephyr)

**Comment by gloparco** [comment]
To your point on getting the latest value, regardless of the primary or fallback storage mechanism, I would think a simple, behind the scenes timestamp could be added as a key/value for this purpose.

**Comment by JosephDuffy** [comment]
> To your point on getting the latest value, regardless of the primary or fallback storage mechanism, I would think a simple, behind the scenes timestamp could be added as a key/value for this purpose.

This appears to be what Zephyr is doing, storing the timestamps in a top-level dictionary.

> I haven't looked through the source code on this project, but it _appears_ to sync the two:
> 
> [Zephyr](https://github.com/ArtSabintsev/Zephyr)

I've looked through Zephyr and I don't think this would conflict with what Persist is doing.

To save implementing this again if you're looking for this functionality I would recommend using `UserDefaults` with Persist and Zephyr to perform the syncing.

If SwiftPM ever adds optional dependencies I would be happy to make this integration easier, but I don't want to add Zephyr as a dependency at this time.

**Comment by gloparco** [comment]
Makes sense...

**Comment by JosephDuffy** [comment]
I'm going to close this for now. If you encounter problems using Persist with Zephyr feel free to open another issue :)
